"""Initial schema from ORM models

Revision ID: dc7aa5fd62af
Revises: 
Create Date: 2026-08-20 20:35:13.805469

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'dc7aa5fd62af'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_name', sa.String(length=64), nullable=False),
    sa.Column('metric_name', sa.String(length=64), nullable=False),
    sa.Column('threshold_type', sa.String(length=32), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('actual_value', sa.Float(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('fired_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analytics_alerts', schema=None) as batch_op:
        batch_op.create_index('ix_alert_fired', ['fired_at'], unique=False)
        batch_op.create_index('ix_alert_name', ['alert_name'], unique=False)

    op.create_table('clustering_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('algorithm', sa.String(length=64), nullable=False),
    sa.Column('hyperparameters', sa.JSON(), nullable=False),
    sa.Column('n_clusters', sa.Integer(), nullable=False),
    sa.Column('training_data_source', sa.String(length=256), nullable=False),
    sa.Column('training_data_size', sa.Integer(), nullable=False),
    sa.Column('training_data_features', sa.JSON(), nullable=False),
    sa.Column('silhouette_score', sa.Float(), nullable=True),
    sa.Column('davies_bouldin_index', sa.Float(), nullable=True),
    sa.Column('per_subgroup_scores', sa.JSON(), nullable=False),
    sa.Column('bias_audit_results', sa.JSON(), nullable=False),
    sa.Column('training_code_commit', sa.String(length=64), nullable=True),
    sa.Column('training_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('staleness_months', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('candidate', 'in_production', 'archived', name='clustering_status'), nullable=False),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner', sa.String(length=128), nullable=True),
    sa.Column('known_limitations', sa.JSON(), nullable=False),
    sa.Column('rollback_plan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_name', 'version', name='uq_clustering_model_name_version')
    )
    with op.batch_alter_table('clustering_models', schema=None) as batch_op:
        batch_op.create_index('ix_clustering_model_status', ['status'], unique=False)

    op.create_table('cohort_retention',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cohort_month', sa.DateTime(timezone=True), nullable=False),
    sa.Column('months_since_signup', sa.Integer(), nullable=False),
    sa.Column('cohort_size', sa.Integer(), nullable=False),
    sa.Column('retained_count', sa.Integer(), nullable=False),
    sa.Column('retention_pct', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cohort_month', 'months_since_signup', name='uq_cohort_retention')
    )
    with op.batch_alter_table('cohort_retention', schema=None) as batch_op:
        batch_op.create_index('ix_cohort_retention_month', ['cohort_month'], unique=False)

    op.create_table('daily_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metric_name', sa.String(length=64), nullable=False),
    sa.Column('tier', sa.String(length=32), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_date', 'metric_name', 'tier', name='uq_daily_metric')
    )
    with op.batch_alter_table('daily_metrics', schema=None) as batch_op:
        batch_op.create_index('ix_daily_metric_name_date', ['metric_name', 'metric_date'], unique=False)

    op.create_table('feature_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usage_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('feature_name', sa.String(length=64), nullable=False),
    sa.Column('adoption_count', sa.Integer(), nullable=False),
    sa.Column('adoption_pct', sa.Float(), nullable=False),
    sa.Column('avg_engagement_minutes', sa.Float(), nullable=False),
    sa.Column('actions_count', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usage_date', 'feature_name', name='uq_feature_usage')
    )
    with op.batch_alter_table('feature_usage', schema=None) as batch_op:
        batch_op.create_index('ix_feature_usage_date', ['usage_date'], unique=False)

    op.create_table('analytics_access_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dashboard_name', sa.String(length=64), nullable=False),
    sa.Column('query_params', sa.JSON(), nullable=True),
    sa.Column('accessed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analytics_access_log', schema=None) as batch_op:
        batch_op.create_index('ix_access_log_user', ['user_id', 'accessed_at'], unique=False)

    op.create_table('analytics_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('event_name', sa.String(length=64), nullable=False),
    sa.Column('event_properties', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.create_index('ix_analytics_event_name_time', ['event_name', 'created_at'], unique=False)
        batch_op.create_index('ix_analytics_event_session', ['session_id', 'created_at'], unique=False)
        batch_op.create_index('ix_analytics_event_user', ['user_id', 'created_at'], unique=False)

    op.create_table('analytics_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('events_json', sa.JSON(), nullable=False),
    sa.Column('device_type', sa.String(length=16), nullable=True),
    sa.Column('browser', sa.String(length=32), nullable=True),
    sa.Column('os', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    with op.batch_alter_table('analytics_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_session_user_time', ['user_id', 'started_at'], unique=False)

    op.create_table('archetype_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cluster_center', sa.JSON(), nullable=False),
    sa.Column('distinguishing_features', sa.JSON(), nullable=False),
    sa.Column('example_players', sa.JSON(), nullable=False),
    sa.Column('player_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['clustering_models.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'cluster_id', name='uq_archetype_model_cluster')
    )
    with op.batch_alter_table('archetype_definitions', schema=None) as batch_op:
        batch_op.create_index('ix_archetype_model', ['model_id'], unique=False)

    op.create_table('clustering_monitoring_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('log_type', sa.String(length=32), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('metric_name', sa.String(length=64), nullable=True),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('alert_triggered', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['clustering_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clustering_monitoring_log', schema=None) as batch_op:
        batch_op.create_index('ix_monitoring_alerts', ['alert_triggered'], unique=False)
        batch_op.create_index('ix_monitoring_model_time', ['model_id', 'logged_at'], unique=False)

    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Enum('free', 'pro', 'enterprise', name='org_tier'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('plan_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('primary_contact_email', sa.String(length=320), nullable=True),
    sa.Column('billing_contact_email', sa.String(length=320), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index('ix_organizations_owner', ['owner_user_id'], unique=False)
        batch_op.create_index('ix_organizations_slug', ['slug'], unique=False)

    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index('ix_comments_author', ['author_user_id'], unique=False)
        batch_op.create_index('ix_comments_org', ['org_id', 'created_at'], unique=False)
        batch_op.create_index('ix_comments_resource', ['resource_type', 'resource_id'], unique=False)

    op.create_table('match_formations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.String(length=64), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('detected_formation', sa.String(length=16), nullable=False),
    sa.Column('stability_json', sa.JSON(), nullable=False),
    sa.Column('conformity_json', sa.JSON(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'team_id', name='uq_formation_match_team')
    )
    with op.batch_alter_table('match_formations', schema=None) as batch_op:
        batch_op.create_index('ix_formation_match', ['match_id'], unique=False)

    op.create_table('match_passing_networks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.String(length=64), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('phase', sa.String(length=32), nullable=False),
    sa.Column('network_json', sa.JSON(), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.Column('style_json', sa.JSON(), nullable=False),
    sa.Column('anomalies_json', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'team_id', 'phase', name='uq_passing_network_match_team_phase')
    )
    with op.batch_alter_table('match_passing_networks', schema=None) as batch_op:
        batch_op.create_index('ix_passing_network_match', ['match_id'], unique=False)

    op.create_table('match_spatial_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.String(length=64), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('analysis_type', sa.String(length=32), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'team_id', 'analysis_type', name='uq_spatial_analysis_match_team_type')
    )
    with op.batch_alter_table('match_spatial_analyses', schema=None) as batch_op:
        batch_op.create_index('ix_spatial_analysis_match', ['match_id'], unique=False)

    op.create_table('org_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('user_added', 'user_removed', 'role_changed', 'resource_created', 'resource_shared', 'resource_deleted', 'comment_added', name='audit_action'), nullable=False),
    sa.Column('performed_by_user_id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('resource_type', sa.String(length=32), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['performed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('org_audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_log_org', ['org_id', 'created_at'], unique=False)
        batch_op.create_index('ix_audit_log_performed_by', ['performed_by_user_id'], unique=False)

    op.create_table('org_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.Enum('owner', 'manager', 'scout', 'viewer', name='org_role'), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('invited_by_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'expired', name='org_invite_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('org_invites', schema=None) as batch_op:
        batch_op.create_index('ix_org_invites_org', ['org_id'], unique=False)
        batch_op.create_index('ix_org_invites_token', ['token_hash'], unique=False)

    op.create_table('org_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'manager', 'scout', 'viewer', name='org_role'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('invited_by_user_id', sa.Integer(), nullable=True),
    sa.Column('permissions_override', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'user_id', name='uq_org_membership')
    )
    with op.batch_alter_table('org_memberships', schema=None) as batch_op:
        batch_op.create_index('ix_org_memberships_org', ['org_id'], unique=False)
        batch_op.create_index('ix_org_memberships_user', ['user_id'], unique=False)

    op.create_table('org_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('data_retention_days', sa.Integer(), nullable=False),
    sa.Column('workspace_name', sa.String(length=128), nullable=True),
    sa.Column('enable_audit_logging', sa.Boolean(), nullable=False),
    sa.Column('allow_public_reporting', sa.Boolean(), nullable=False),
    sa.Column('require_2fa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id')
    )
    with op.batch_alter_table('org_settings', schema=None) as batch_op:
        batch_op.create_index('ix_org_settings_org', ['org_id'], unique=False)

    op.create_table('archetype_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('distance_to_center', sa.Float(), nullable=False),
    sa.Column('top_distinguishing_features', sa.JSON(), nullable=False),
    sa.Column('computed_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_outlier', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['clustering_models.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'model_id', 'snapshot_date', name='uq_archetype_assignment_player_model_date')
    )
    with op.batch_alter_table('archetype_assignments', schema=None) as batch_op:
        batch_op.create_index('ix_archetype_assignment_model', ['model_id', 'cluster_id'], unique=False)
        batch_op.create_index('ix_archetype_assignment_player', ['player_id'], unique=False)

    op.create_table('contract_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('current_team_id', sa.Integer(), nullable=True),
    sa.Column('contract_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contract_value_per_year_eur', sa.Float(), nullable=True),
    sa.Column('contract_status', sa.Enum('active', 'expiring_next_season', 'expired', 'on_loan', name='contract_status'), nullable=False),
    sa.Column('source', sa.Enum('transfermarkt', 'understat_transfer', 'instat', 'manual', name='market_source'), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['current_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'source', 'snapshot_date', name='uq_contract_status_player_source_date')
    )
    with op.batch_alter_table('contract_status', schema=None) as batch_op:
        batch_op.create_index('ix_contract_player', ['player_id'], unique=False)

    op.create_table('market_valuations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('transfermarkt', 'understat_transfer', 'instat', 'manual', name='market_source'), nullable=False),
    sa.Column('valuation_amount_eur', sa.Float(), nullable=False),
    sa.Column('valuation_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('low_range', sa.Float(), nullable=True),
    sa.Column('high_range', sa.Float(), nullable=True),
    sa.Column('confidence_level', sa.Enum('high', 'medium', 'low', name='valuation_confidence'), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'source', 'valuation_date', name='uq_market_valuation_player_source_date')
    )
    with op.batch_alter_table('market_valuations', schema=None) as batch_op:
        batch_op.create_index('ix_market_valuation_date', ['valuation_date'], unique=False)
        batch_op.create_index('ix_market_valuation_player', ['player_id', 'valuation_date'], unique=False)

    op.create_table('mentions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('mentioned_user_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'read', name='mention_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['mentioned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mentions', schema=None) as batch_op:
        batch_op.create_index('ix_mentions_comment', ['comment_id'], unique=False)
        batch_op.create_index('ix_mentions_user', ['mentioned_user_id', 'status'], unique=False)

    op.create_table('transfer_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('from_team_id', sa.Integer(), nullable=True),
    sa.Column('to_team_id', sa.Integer(), nullable=False),
    sa.Column('transfer_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reported_fee_eur', sa.Float(), nullable=True),
    sa.Column('transfer_type', sa.Enum('permanent', 'loan', 'free_agent', name='transfer_type'), nullable=False),
    sa.Column('status', sa.Enum('confirmed', 'reported', name='transfer_status'), nullable=False),
    sa.Column('source', sa.Enum('transfermarkt', 'understat_transfer', 'instat', 'manual', name='market_source'), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['from_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['to_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transfer_history', schema=None) as batch_op:
        batch_op.create_index('ix_transfer_date', ['transfer_date'], unique=False)
        batch_op.create_index('ix_transfer_player', ['player_id'], unique=False)
        batch_op.create_index('ix_transfer_to_team', ['to_team_id'], unique=False)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_org_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('visibility', sa.Enum('personal', 'org_members', 'restricted', name='resource_visibility'), nullable=False))
        batch_op.add_column(sa.Column('created_by_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'organizations', ['owner_org_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['created_by_user_id'], ['id'])

    with op.batch_alter_table('saved_searches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_org_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('visibility', sa.Enum('personal', 'org_members', 'restricted', name='resource_visibility'), nullable=False))
        batch_op.add_column(sa.Column('created_by_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['created_by_user_id'], ['id'])
        batch_op.create_foreign_key(None, 'organizations', ['owner_org_id'], ['id'])

    with op.batch_alter_table('shortlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_org_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('visibility', sa.Enum('personal', 'org_members', 'restricted', name='resource_visibility'), nullable=False))
        batch_op.add_column(sa.Column('created_by_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('restricted_access', sa.JSON(), nullable=True))
        batch_op.create_foreign_key(None, 'organizations', ['owner_org_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['created_by_user_id'], ['id'])

    with op.batch_alter_table('watches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_org_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('visibility', sa.Enum('personal', 'org_members', 'restricted', name='resource_visibility'), nullable=False))
        batch_op.add_column(sa.Column('created_by_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'organizations', ['owner_org_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['created_by_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_by_user_id')
        batch_op.drop_column('visibility')
        batch_op.drop_column('owner_org_id')

    with op.batch_alter_table('shortlists', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('restricted_access')
        batch_op.drop_column('created_by_user_id')
        batch_op.drop_column('visibility')
        batch_op.drop_column('owner_org_id')

    with op.batch_alter_table('saved_searches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_by_user_id')
        batch_op.drop_column('visibility')
        batch_op.drop_column('owner_org_id')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_by_user_id')
        batch_op.drop_column('visibility')
        batch_op.drop_column('owner_org_id')

    with op.batch_alter_table('transfer_history', schema=None) as batch_op:
        batch_op.drop_index('ix_transfer_to_team')
        batch_op.drop_index('ix_transfer_player')
        batch_op.drop_index('ix_transfer_date')

    op.drop_table('transfer_history')
    with op.batch_alter_table('mentions', schema=None) as batch_op:
        batch_op.drop_index('ix_mentions_user')
        batch_op.drop_index('ix_mentions_comment')

    op.drop_table('mentions')
    with op.batch_alter_table('market_valuations', schema=None) as batch_op:
        batch_op.drop_index('ix_market_valuation_player')
        batch_op.drop_index('ix_market_valuation_date')

    op.drop_table('market_valuations')
    with op.batch_alter_table('contract_status', schema=None) as batch_op:
        batch_op.drop_index('ix_contract_player')

    op.drop_table('contract_status')
    with op.batch_alter_table('archetype_assignments', schema=None) as batch_op:
        batch_op.drop_index('ix_archetype_assignment_player')
        batch_op.drop_index('ix_archetype_assignment_model')

    op.drop_table('archetype_assignments')
    with op.batch_alter_table('org_settings', schema=None) as batch_op:
        batch_op.drop_index('ix_org_settings_org')

    op.drop_table('org_settings')
    with op.batch_alter_table('org_memberships', schema=None) as batch_op:
        batch_op.drop_index('ix_org_memberships_user')
        batch_op.drop_index('ix_org_memberships_org')

    op.drop_table('org_memberships')
    with op.batch_alter_table('org_invites', schema=None) as batch_op:
        batch_op.drop_index('ix_org_invites_token')
        batch_op.drop_index('ix_org_invites_org')

    op.drop_table('org_invites')
    with op.batch_alter_table('org_audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_log_performed_by')
        batch_op.drop_index('ix_audit_log_org')

    op.drop_table('org_audit_log')
    with op.batch_alter_table('match_spatial_analyses', schema=None) as batch_op:
        batch_op.drop_index('ix_spatial_analysis_match')

    op.drop_table('match_spatial_analyses')
    with op.batch_alter_table('match_passing_networks', schema=None) as batch_op:
        batch_op.drop_index('ix_passing_network_match')

    op.drop_table('match_passing_networks')
    with op.batch_alter_table('match_formations', schema=None) as batch_op:
        batch_op.drop_index('ix_formation_match')

    op.drop_table('match_formations')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index('ix_comments_resource')
        batch_op.drop_index('ix_comments_org')
        batch_op.drop_index('ix_comments_author')

    op.drop_table('comments')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index('ix_organizations_slug')
        batch_op.drop_index('ix_organizations_owner')

    op.drop_table('organizations')
    with op.batch_alter_table('clustering_monitoring_log', schema=None) as batch_op:
        batch_op.drop_index('ix_monitoring_model_time')
        batch_op.drop_index('ix_monitoring_alerts')

    op.drop_table('clustering_monitoring_log')
    with op.batch_alter_table('archetype_definitions', schema=None) as batch_op:
        batch_op.drop_index('ix_archetype_model')

    op.drop_table('archetype_definitions')
    with op.batch_alter_table('analytics_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_session_user_time')

    op.drop_table('analytics_sessions')
    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.drop_index('ix_analytics_event_user')
        batch_op.drop_index('ix_analytics_event_session')
        batch_op.drop_index('ix_analytics_event_name_time')

    op.drop_table('analytics_events')
    with op.batch_alter_table('analytics_access_log', schema=None) as batch_op:
        batch_op.drop_index('ix_access_log_user')

    op.drop_table('analytics_access_log')
    with op.batch_alter_table('feature_usage', schema=None) as batch_op:
        batch_op.drop_index('ix_feature_usage_date')

    op.drop_table('feature_usage')
    with op.batch_alter_table('daily_metrics', schema=None) as batch_op:
        batch_op.drop_index('ix_daily_metric_name_date')

    op.drop_table('daily_metrics')
    with op.batch_alter_table('cohort_retention', schema=None) as batch_op:
        batch_op.drop_index('ix_cohort_retention_month')

    op.drop_table('cohort_retention')
    with op.batch_alter_table('clustering_models', schema=None) as batch_op:
        batch_op.drop_index('ix_clustering_model_status')

    op.drop_table('clustering_models')
    with op.batch_alter_table('analytics_alerts', schema=None) as batch_op:
        batch_op.drop_index('ix_alert_name')
        batch_op.drop_index('ix_alert_fired')

    op.drop_table('analytics_alerts')
    # ### end Alembic commands ###
