import { expect, test } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";

/**
 * Phase 3 Part D quality gates — the features DataMB doesn't have, verified
 * against the seeded fixture-demo stack (scripts/e2e-server.sh):
 *
 *   1. Shot/pass maps render ONLY for players with data_coverage confirmation,
 *      and the accessible data-table fallback shows the same real rows (B2/B3).
 *   2. Honest unavailability message for a player WITHOUT event coverage —
 *      Kevin De Bruyne has no StatsBomb events in the seed; the map entry
 *      point must NOT render, and the factual note must (Part B4).
 *   3. axe is green specifically on the pitch-diagram components (their SVG +
 *      data-table fallback are in the a11y audit of the covered player page).
 *   4. Embed widgets render a real chart from a fresh URL with no prior client
 *      state (Part C3 / gate 6) — the embed page is the iframe target.
 *   5. Trend tool: a player with multi-snapshot history renders a real trend
 *      line, not an empty/error state (Part A e2e, previously uncovered).
 */

const HIGHLY_COVERED_PLAYER = "/players/erling-haaland"; // has StatsBomb demo events
const UNCOVERED_PLAYER = "/players/kevin-de-bruyne"; // no events in seed -> B4 note

test("shot map renders real data with an accessible data-table fallback", async ({ page }) => {
  await page.goto(HIGHLY_COVERED_PLAYER);

  // The coverage-gated section must render the map (not the unavailability note).
  const section = page.getByRole("region", { name: /shot and pass maps/i });
  await expect(section).toBeVisible({ timeout: 15_000 });

  // The pitch diagram itself renders with shot markers (class on each marker).
  await expect(page.locator(".pitch")).toBeVisible({ timeout: 15_000 });
  const markers = page.locator(".pitch-shot");
  await expect(markers.first()).toBeVisible({ timeout: 10_000 });
  expect(await markers.count()).toBeGreaterThan(0);

  // Outcome legend is shape + label + count — never colour alone. The list
  // carries the visible text labels; the shape glyphs sit inside each item.
  const legend = page.getByRole("list", { name: "Shot outcomes" });
  await expect(legend).toBeVisible();
  await expect(legend).toContainText("Goal");
  await expect(legend).toContainText("Saved");
  await expect(legend).toContainText("Off target");

  // Data-table fallback: toggle reveals a structured table with the same rows.
  await page.getByRole("button", { name: "Show data table" }).click();
  const table = page.locator("table[aria-label*='Shots for']");
  await expect(table).toBeVisible({ timeout: 10_000 });
  const rows = table.locator("tbody tr");
  expect(await rows.count()).toBeGreaterThan(0);
  // Every row carries the real outcome text, not an empty placeholder.
  await expect(rows.first()).not.toBeEmpty();

  // Passes tab also renders and its table fallback works.
  await page.getByRole("button", { name: "Passes" }).click();
  await expect(page.locator(".pitch-pass").first()).toBeVisible({ timeout: 15_000 });
  await page.getByRole("button", { name: "Show data table" }).click();
  await expect(page.locator("table[aria-label*='Passes for']").first()).toBeVisible({ timeout: 10_000 });
});

test("honest unavailability note renders for a player without event coverage", async ({ page }) => {
  await page.goto(UNCOVERED_PLAYER);

  // The section renders the FACTUAL note — never a map, never a grayed-out
  // "coming soon" that implies universal coverage (Part B4 / Never-List #8).
  const note = page.getByText(/Event-level data for this player is not yet available/i);
  await expect(note).toBeVisible({ timeout: 15_000 });

  // And the pitch diagram must NOT render for this player.
  await expect(page.locator(".pitch")).toHaveCount(0);
});

test("axe is green on the pitch components and their data-table fallback", async ({ page }) => {
  // The covered player's page renders the shot/pass maps + data-table toggle,
  // so this audit exercises the Phase 3 pitch components specifically.
  await page.goto(HIGHLY_COVERED_PLAYER);
  await page.getByRole("region", { name: /shot and pass maps/i }).waitFor({ timeout: 15_000 });
  await page.getByRole("button", { name: "Show data table" }).click();
  await page.waitForLoadState("networkidle");

  const results = await new AxeBuilder({ page }).analyze();
  expect(
    results.violations,
    `axe violations on pitch components: ${results.violations.map((v) => v.id).join(", ")}`,
  ).toEqual([]);
});

test("radar embed widget renders the real chart from a fresh URL", async ({ page }) => {
  // The exact iframe src generated by SharePanel (share.test.ts), opened with
  // NO prior client state — the embed must reproduce the chart from the query.
  await page.goto("/embed/radar?players=erling-haaland,mohamed-salah&mode=pct");
  const radar = page.locator("svg[role='img'][aria-label*='radar' i], svg[aria-label*='Radar' i]").first();
  await expect(radar).toBeVisible({ timeout: 15_000 });
  // Real data: both players' names appear in the widget (legend/labels).
  await expect(page.locator("text=Erling Haaland").first()).toBeVisible();
  await expect(page.locator("text=Mohamed Salah").first()).toBeVisible();
  // Attribution (the backlink mechanism) is part of the widget.
  await expect(page.getByText(/Powered by Statlas/i)).toBeVisible();
});

test("trend embed widget renders a real line chart from a fresh URL", async ({ page }) => {
  await page.goto("/embed/trend?players=erling-haaland&metrics=si_gls_p90&window=5&mode=pct");
  const svg = page.locator(".trend-svg").first();
  await expect(svg).toBeVisible({ timeout: 15_000 });
  await expect(page.locator("text=Erling Haaland").first()).toBeVisible();
  await expect(page.getByText(/Powered by Statlas/i)).toBeVisible();
});

test("trend tool renders a real trend for a player with snapshot history", async ({ page }) => {
  await page.goto("/trend");

  const search = page.getByPlaceholder(/Haaland' or 'Salah/);
  await search.fill("Haaland");
  const option = page.getByRole("option", { name: /Erling Haaland/ }).first();
  await expect(option).toBeVisible({ timeout: 10_000 });
  await option.click();

  // A real trend renders (not the empty/insufficient/error state). In the
  // fixture seed percentiles are constant across snapshots, so the line is
  // flat — assert on the chart + the numeric end-value labels that always
  // accompany a line (numbers, never colour alone).
  const svg = page.locator(".trend-svg").first();
  await expect(svg).toBeVisible({ timeout: 15_000 });
  await expect(page.locator(".trend-end-label").first()).toBeVisible({ timeout: 10_000 });
  // The legend names the player and metric with a value — real data on screen.
  await expect(page.locator(".radar-legend").getByText(/Erling Haaland/).first()).toBeVisible({
    timeout: 10_000,
  });
  // Share panel appears once lines exist (Phase 3 Part C).
  await expect(page.getByRole("region", { name: /share this chart/i })).toBeVisible();
});
