const PRICING_TIERS = [
  {
    name: "Free",
    price: "\u20ac0",
    period: "/month",
    description: "Get started with essentials",
    cta: "Sign up free",
    ctaHref: "/register",
    highlighted: false,
    features: [
      { text: "Unlimited player searches", included: true },
      { text: "Radar comparisons (2 players)", included: true },
      { text: "5 saved shortlists", included: true },
      { text: "10 saved searches", included: true },
      { text: "1 report/month", included: true },
      { text: "Team workspace", included: false },
      { text: "API access", included: false },
    ],
  },
  {
    name: "Pro",
    price: "\u20ac7",
    period: "/month",
    description: "For professional scouts",
    cta: "Start 14-day free trial",
    ctaHref: "/register?plan=pro",
    highlighted: true,
    badge: "Most popular",
    features: [
      { text: "Everything in Free", included: true },
      { text: "Radar comparisons (4 players)", included: true },
      { text: "Unlimited shortlists", included: true },
      { text: "10 reports/month", included: true },
      { text: "Team workspace (5 members)", included: true },
      { text: "Shot/pass maps", included: true },
      { text: "Priority support", included: true },
    ],
  },
  {
    name: "Business",
    price: "\u20ac49",
    period: "/month",
    description: "For media and agencies",
    cta: "Contact sales",
    ctaHref: "/contact",
    highlighted: false,
    features: [
      { text: "Everything in Pro", included: true },
      { text: "Unlimited team members", included: true },
      { text: "API access (1,000 req/day)", included: true },
      { text: "Custom integrations", included: true },
      { text: "Dedicated support", included: true },
      { text: "SSO/SAML", included: true },
      { text: "SLA: 99.95% uptime", included: true },
    ],
  },
];

const USE_CASES = [
  { title: "For Scouts", quote: "Statlas cuts my research time in half. I trust every number.", href: "/use-cases/scout" },
  { title: "For Agents", quote: "I use Statlas to negotiate better contracts with data-backed valuations.", href: "/use-cases/agent" },
  { title: "For Analysts", quote: "Finally, stats with the methods published. I can audit everything.", href: "/use-cases/analyst" },
  { title: "For Media", quote: "Our viewers trust our analysis because we explain every stat.", href: "/use-cases/media" },
  { title: "For Fans", quote: "I finally understand what percentiles mean. This is how stats should be presented.", href: "/use-cases/fan" },
];

const FEATURES = [
  { icon: Radar, title: "Player Comparison", desc: "Compare up to 4 players side-by-side on radar charts. See strengths and weaknesses instantly.", href: "/compare" },
  { icon: TrendingUp, title: "Trend Analysis", desc: "Weekly snapshots show real improvement. Filled gaps are honest, never interpolated.", href: "/trend" },
  { icon: Map, title: "Shot & Pass Maps", desc: "Every shot, pass, and progressive action mapped. Understand where the magic happens.", href: "/data-coverage" },
  { icon: FileText, title: "AI Reports", desc: "Grounded scouting reports verified against real data. No fabricated stats.", href: "/reports" },
  { icon: FolderOpen, title: "Workspace", desc: "Shortlists, notes, tags, and a six-stage status pipeline for real decision processes.", href: "/workspace" },
  { icon: Search, title: "Structured Search", desc: "Multi-condition search across position, age, league, and 12+ metrics.", href: "/search" },
  { icon: Bell, title: "Watchlist & Alerts", desc: "Follow players and get notified on percentile movement and club changes.", href: "/watchlist" },
  { icon: Code, title: "API Access", desc: "Versioned REST API with OpenAPI spec. Embed charts, export data, build integrations.", href: "/api-docs" },
];
